// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlas.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Did                   string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationCode string                 `protobuf:"bytes,4,opt,name=email_verification_code,json=emailVerificationCode,proto3" json:"email_verification_code,omitempty"`
	EmailConfirmed        bool                   `protobuf:"varint,5,opt,name=email_confirmed,json=emailConfirmed,proto3" json:"email_confirmed,omitempty"`
	PasswordHash          []byte                 `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	SigningKey            []byte                 `protobuf:"bytes,7,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	Handle                string                 `protobuf:"bytes,8,opt,name=handle,proto3" json:"handle,omitempty"`
	Active                bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	RotationKeys          [][]byte               `protobuf:"bytes,10,rep,name=rotation_keys,json=rotationKeys,proto3" json:"rotation_keys,omitempty"`
	RefreshTokens         []*RefreshToken        `protobuf:"bytes,11,rep,name=refresh_tokens,json=refreshTokens,proto3" json:"refresh_tokens,omitempty"`
	Head                  string                 `protobuf:"bytes,12,opt,name=head,proto3" json:"head,omitempty"`
	Rev                   string                 `protobuf:"bytes,13,opt,name=rev,proto3" json:"rev,omitempty"`
	PdsHost               string                 `protobuf:"bytes,14,opt,name=pds_host,json=pdsHost,proto3" json:"pds_host,omitempty"` // hostname of the PDS this actor belongs to
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Actor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Actor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Actor) GetEmailVerificationCode() string {
	if x != nil {
		return x.EmailVerificationCode
	}
	return ""
}

func (x *Actor) GetEmailConfirmed() bool {
	if x != nil {
		return x.EmailConfirmed
	}
	return false
}

func (x *Actor) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *Actor) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *Actor) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Actor) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Actor) GetRotationKeys() [][]byte {
	if x != nil {
		return x.RotationKeys
	}
	return nil
}

func (x *Actor) GetRefreshTokens() []*RefreshToken {
	if x != nil {
		return x.RefreshTokens
	}
	return nil
}

func (x *Actor) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *Actor) GetRev() string {
	if x != nil {
		return x.Rev
	}
	return ""
}

func (x *Actor) GetPdsHost() string {
	if x != nil {
		return x.PdsHost
	}
	return ""
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_atlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RefreshToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Record represents a single record in a user's repo
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Did           string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"` // NSID, e.g. "app.bsky.feed.post"
	Rkey          string                 `protobuf:"bytes,3,opt,name=rkey,proto3" json:"rkey,omitempty"`             // record key (TID or user-specified)
	Cid           string                 `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`               // CID of the record content
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`           // CBOR-encoded record data
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_atlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Record) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Record) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *Record) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_atlas_proto protoreflect.FileDescriptor

const file_atlas_proto_rawDesc = "" +
	"\n" +
	"\vatlas.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x03\n" +
	"\x05Actor\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x126\n" +
	"\x17email_verification_code\x18\x04 \x01(\tR\x15emailVerificationCode\x12'\n" +
	"\x0femail_confirmed\x18\x05 \x01(\bR\x0eemailConfirmed\x12#\n" +
	"\rpassword_hash\x18\x06 \x01(\fR\fpasswordHash\x12\x1f\n" +
	"\vsigning_key\x18\a \x01(\fR\n" +
	"signingKey\x12\x16\n" +
	"\x06handle\x18\b \x01(\tR\x06handle\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12#\n" +
	"\rrotation_keys\x18\n" +
	" \x03(\fR\frotationKeys\x12:\n" +
	"\x0erefresh_tokens\x18\v \x03(\v2\x13.types.RefreshTokenR\rrefreshTokens\x12\x12\n" +
	"\x04head\x18\f \x01(\tR\x04head\x12\x10\n" +
	"\x03rev\x18\r \x01(\tR\x03rev\x12\x19\n" +
	"\bpds_host\x18\x0e \x01(\tR\apdsHost\"\x9a\x01\n" +
	"\fRefreshToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xb1\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x03 \x01(\tR\x04rkey\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\tR\x03cid\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB*Z(github.com/jcalabro/atlas/internal/typesb\x06proto3"

var (
	file_atlas_proto_rawDescOnce sync.Once
	file_atlas_proto_rawDescData []byte
)

func file_atlas_proto_rawDescGZIP() []byte {
	file_atlas_proto_rawDescOnce.Do(func() {
		file_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)))
	})
	return file_atlas_proto_rawDescData
}

var file_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atlas_proto_goTypes = []any{
	(*Actor)(nil),                 // 0: types.Actor
	(*RefreshToken)(nil),          // 1: types.RefreshToken
	(*Record)(nil),                // 2: types.Record
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_atlas_proto_depIdxs = []int32{
	3, // 0: types.Actor.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: types.Actor.refresh_tokens:type_name -> types.RefreshToken
	3, // 2: types.RefreshToken.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: types.RefreshToken.expires_at:type_name -> google.protobuf.Timestamp
	3, // 4: types.Record.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_atlas_proto_init() }
func file_atlas_proto_init() {
	if File_atlas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atlas_proto_goTypes,
		DependencyIndexes: file_atlas_proto_depIdxs,
		MessageInfos:      file_atlas_proto_msgTypes,
	}.Build()
	File_atlas_proto = out.File
	file_atlas_proto_goTypes = nil
	file_atlas_proto_depIdxs = nil
}
