// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlas.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Did                   string                 `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerificationCode string                 `protobuf:"bytes,4,opt,name=email_verification_code,json=emailVerificationCode,proto3" json:"email_verification_code,omitempty"`
	EmailConfirmed        bool                   `protobuf:"varint,5,opt,name=email_confirmed,json=emailConfirmed,proto3" json:"email_confirmed,omitempty"`
	PasswordHash          []byte                 `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	SigningKey            []byte                 `protobuf:"bytes,7,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	Handle                string                 `protobuf:"bytes,8,opt,name=handle,proto3" json:"handle,omitempty"`
	Active                bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Actor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Actor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Actor) GetEmailVerificationCode() string {
	if x != nil {
		return x.EmailVerificationCode
	}
	return ""
}

func (x *Actor) GetEmailConfirmed() bool {
	if x != nil {
		return x.EmailConfirmed
	}
	return false
}

func (x *Actor) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *Actor) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *Actor) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Actor) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_atlas_proto protoreflect.FileDescriptor

const file_atlas_proto_rawDesc = "" +
	"\n" +
	"\vatlas.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x02\n" +
	"\x05Actor\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x126\n" +
	"\x17email_verification_code\x18\x04 \x01(\tR\x15emailVerificationCode\x12'\n" +
	"\x0femail_confirmed\x18\x05 \x01(\bR\x0eemailConfirmed\x12#\n" +
	"\rpassword_hash\x18\x06 \x01(\fR\fpasswordHash\x12\x1f\n" +
	"\vsigning_key\x18\a \x01(\fR\n" +
	"signingKey\x12\x16\n" +
	"\x06handle\x18\b \x01(\tR\x06handle\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06activeB*Z(github.com/jcalabro/atlas/internal/typesb\x06proto3"

var (
	file_atlas_proto_rawDescOnce sync.Once
	file_atlas_proto_rawDescData []byte
)

func file_atlas_proto_rawDescGZIP() []byte {
	file_atlas_proto_rawDescOnce.Do(func() {
		file_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)))
	})
	return file_atlas_proto_rawDescData
}

var file_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_atlas_proto_goTypes = []any{
	(*Actor)(nil),                 // 0: types.Actor
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_atlas_proto_depIdxs = []int32{
	1, // 0: types.Actor.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_atlas_proto_init() }
func file_atlas_proto_init() {
	if File_atlas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atlas_proto_goTypes,
		DependencyIndexes: file_atlas_proto_depIdxs,
		MessageInfos:      file_atlas_proto_msgTypes,
	}.Build()
	File_atlas_proto = out.File
	file_atlas_proto_goTypes = nil
	file_atlas_proto_depIdxs = nil
}
