version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
      exclude-functions:
        - "fmt.Fprintf"
      verbose: true
    gocritic:
      enable-all: true

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
