// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atlas.proto

package typesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	types "github.com/jcalabro/atlas/internal/types"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "types.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServicePingProcedure is the fully-qualified name of the Service's Ping RPC.
	ServicePingProcedure = "/types.Service/Ping"
	// ServiceGetRecordsProcedure is the fully-qualified name of the Service's GetRecords RPC.
	ServiceGetRecordsProcedure = "/types.Service/GetRecords"
	// ServiceGetActorsProcedure is the fully-qualified name of the Service's GetActors RPC.
	ServiceGetActorsProcedure = "/types.Service/GetActors"
	// ServiceQueryProcedure is the fully-qualified name of the Service's Query RPC.
	ServiceQueryProcedure = "/types.Service/Query"
)

// ServiceClient is a client for the types.Service service.
type ServiceClient interface {
	Ping(context.Context, *connect.Request[types.PingRequest]) (*connect.Response[types.PingResponse], error)
	GetRecords(context.Context, *connect.Request[types.GetRecordsRequest]) (*connect.Response[types.GetRecordsResponse], error)
	GetActors(context.Context, *connect.Request[types.GetActorsRequest]) (*connect.Response[types.GetActorsResponse], error)
	Query(context.Context, *connect.Request[types.QueryRequest]) (*connect.Response[types.QueryResponse], error)
}

// NewServiceClient constructs a client for the types.Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := types.File_atlas_proto.Services().ByName("Service").Methods()
	return &serviceClient{
		ping: connect.NewClient[types.PingRequest, types.PingResponse](
			httpClient,
			baseURL+ServicePingProcedure,
			connect.WithSchema(serviceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		getRecords: connect.NewClient[types.GetRecordsRequest, types.GetRecordsResponse](
			httpClient,
			baseURL+ServiceGetRecordsProcedure,
			connect.WithSchema(serviceMethods.ByName("GetRecords")),
			connect.WithClientOptions(opts...),
		),
		getActors: connect.NewClient[types.GetActorsRequest, types.GetActorsResponse](
			httpClient,
			baseURL+ServiceGetActorsProcedure,
			connect.WithSchema(serviceMethods.ByName("GetActors")),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[types.QueryRequest, types.QueryResponse](
			httpClient,
			baseURL+ServiceQueryProcedure,
			connect.WithSchema(serviceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	ping       *connect.Client[types.PingRequest, types.PingResponse]
	getRecords *connect.Client[types.GetRecordsRequest, types.GetRecordsResponse]
	getActors  *connect.Client[types.GetActorsRequest, types.GetActorsResponse]
	query      *connect.Client[types.QueryRequest, types.QueryResponse]
}

// Ping calls types.Service.Ping.
func (c *serviceClient) Ping(ctx context.Context, req *connect.Request[types.PingRequest]) (*connect.Response[types.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// GetRecords calls types.Service.GetRecords.
func (c *serviceClient) GetRecords(ctx context.Context, req *connect.Request[types.GetRecordsRequest]) (*connect.Response[types.GetRecordsResponse], error) {
	return c.getRecords.CallUnary(ctx, req)
}

// GetActors calls types.Service.GetActors.
func (c *serviceClient) GetActors(ctx context.Context, req *connect.Request[types.GetActorsRequest]) (*connect.Response[types.GetActorsResponse], error) {
	return c.getActors.CallUnary(ctx, req)
}

// Query calls types.Service.Query.
func (c *serviceClient) Query(ctx context.Context, req *connect.Request[types.QueryRequest]) (*connect.Response[types.QueryResponse], error) {
	return c.query.CallUnary(ctx, req)
}

// ServiceHandler is an implementation of the types.Service service.
type ServiceHandler interface {
	Ping(context.Context, *connect.Request[types.PingRequest]) (*connect.Response[types.PingResponse], error)
	GetRecords(context.Context, *connect.Request[types.GetRecordsRequest]) (*connect.Response[types.GetRecordsResponse], error)
	GetActors(context.Context, *connect.Request[types.GetActorsRequest]) (*connect.Response[types.GetActorsResponse], error)
	Query(context.Context, *connect.Request[types.QueryRequest]) (*connect.Response[types.QueryResponse], error)
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := types.File_atlas_proto.Services().ByName("Service").Methods()
	servicePingHandler := connect.NewUnaryHandler(
		ServicePingProcedure,
		svc.Ping,
		connect.WithSchema(serviceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	serviceGetRecordsHandler := connect.NewUnaryHandler(
		ServiceGetRecordsProcedure,
		svc.GetRecords,
		connect.WithSchema(serviceMethods.ByName("GetRecords")),
		connect.WithHandlerOptions(opts...),
	)
	serviceGetActorsHandler := connect.NewUnaryHandler(
		ServiceGetActorsProcedure,
		svc.GetActors,
		connect.WithSchema(serviceMethods.ByName("GetActors")),
		connect.WithHandlerOptions(opts...),
	)
	serviceQueryHandler := connect.NewUnaryHandler(
		ServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(serviceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	return "/types.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServicePingProcedure:
			servicePingHandler.ServeHTTP(w, r)
		case ServiceGetRecordsProcedure:
			serviceGetRecordsHandler.ServeHTTP(w, r)
		case ServiceGetActorsProcedure:
			serviceGetActorsHandler.ServeHTTP(w, r)
		case ServiceQueryProcedure:
			serviceQueryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Ping(context.Context, *connect.Request[types.PingRequest]) (*connect.Response[types.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("types.Service.Ping is not implemented"))
}

func (UnimplementedServiceHandler) GetRecords(context.Context, *connect.Request[types.GetRecordsRequest]) (*connect.Response[types.GetRecordsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("types.Service.GetRecords is not implemented"))
}

func (UnimplementedServiceHandler) GetActors(context.Context, *connect.Request[types.GetActorsRequest]) (*connect.Response[types.GetActorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("types.Service.GetActors is not implemented"))
}

func (UnimplementedServiceHandler) Query(context.Context, *connect.Request[types.QueryRequest]) (*connect.Response[types.QueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("types.Service.Query is not implemented"))
}
