// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto

package atlas

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServicePingProcedure is the fully-qualified name of the Service's Ping RPC.
	ServicePingProcedure = "/atlas.Service/Ping"
	// ServiceGetRecordProcedure is the fully-qualified name of the Service's GetRecord RPC.
	ServiceGetRecordProcedure = "/atlas.Service/GetRecord"
)

// ServiceClient is a client for the Service service.
type ServiceClient interface {
	// Sends a ping to the server
	Ping(context.Context, *connect.Request[PingRequest]) (*connect.Response[PingResponse], error)
	// GetRecord retrieves a single record by its AT URI or by its component parts.
	GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error)
}

// NewServiceClient constructs a client for the Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceMethods := File_atlas_proto.Services().ByName("Service").Methods()
	return &serviceClient{
		ping: connect.NewClient[PingRequest, PingResponse](
			httpClient,
			baseURL+ServicePingProcedure,
			connect.WithSchema(serviceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		getRecord: connect.NewClient[GetRecordRequest, GetRecordResponse](
			httpClient,
			baseURL+ServiceGetRecordProcedure,
			connect.WithSchema(serviceMethods.ByName("GetRecord")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	ping      *connect.Client[PingRequest, PingResponse]
	getRecord *connect.Client[GetRecordRequest, GetRecordResponse]
}

// Ping calls Service.Ping.
func (c *serviceClient) Ping(ctx context.Context, req *connect.Request[PingRequest]) (*connect.Response[PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// GetRecord calls Service.GetRecord.
func (c *serviceClient) GetRecord(ctx context.Context, req *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error) {
	return c.getRecord.CallUnary(ctx, req)
}

// ServiceHandler is an implementation of the Service service.
type ServiceHandler interface {
	// Sends a ping to the server
	Ping(context.Context, *connect.Request[PingRequest]) (*connect.Response[PingResponse], error)
	// GetRecord retrieves a single record by its AT URI or by its component parts.
	GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error)
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceMethods := File_atlas_proto.Services().ByName("Service").Methods()
	servicePingHandler := connect.NewUnaryHandler(
		ServicePingProcedure,
		svc.Ping,
		connect.WithSchema(serviceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	serviceGetRecordHandler := connect.NewUnaryHandler(
		ServiceGetRecordProcedure,
		svc.GetRecord,
		connect.WithSchema(serviceMethods.ByName("GetRecord")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atlas.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServicePingProcedure:
			servicePingHandler.ServeHTTP(w, r)
		case ServiceGetRecordProcedure:
			serviceGetRecordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Ping(context.Context, *connect.Request[PingRequest]) (*connect.Response[PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("Service.Ping is not implemented"))
}

func (UnimplementedServiceHandler) GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("Service.GetRecord is not implemented"))
}
