// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto

package atlas

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AtlasServiceName is the fully-qualified name of the AtlasService service.
	AtlasServiceName = "AtlasService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AtlasServiceGetRecordProcedure is the fully-qualified name of the AtlasService's GetRecord RPC.
	AtlasServiceGetRecordProcedure = "/atlas.AtlasService/GetRecord"
)

// AtlasServiceClient is a client for the AtlasService service.
type AtlasServiceClient interface {
	// GetRecord retrieves a single record by its AT URI or by its component parts.
	GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error)
}

// NewAtlasServiceClient constructs a client for the AtlasService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAtlasServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AtlasServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	atlasServiceMethods := File_atlas_proto.Services().ByName("AtlasService").Methods()
	return &atlasServiceClient{
		getRecord: connect.NewClient[GetRecordRequest, GetRecordResponse](
			httpClient,
			baseURL+AtlasServiceGetRecordProcedure,
			connect.WithSchema(atlasServiceMethods.ByName("GetRecord")),
			connect.WithClientOptions(opts...),
		),
	}
}

// atlasServiceClient implements AtlasServiceClient.
type atlasServiceClient struct {
	getRecord *connect.Client[GetRecordRequest, GetRecordResponse]
}

// GetRecord calls AtlasService.GetRecord.
func (c *atlasServiceClient) GetRecord(ctx context.Context, req *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error) {
	return c.getRecord.CallUnary(ctx, req)
}

// AtlasServiceHandler is an implementation of the AtlasService service.
type AtlasServiceHandler interface {
	// GetRecord retrieves a single record by its AT URI or by its component parts.
	GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error)
}

// NewAtlasServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAtlasServiceHandler(svc AtlasServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	atlasServiceMethods := File_atlas_proto.Services().ByName("AtlasService").Methods()
	atlasServiceGetRecordHandler := connect.NewUnaryHandler(
		AtlasServiceGetRecordProcedure,
		svc.GetRecord,
		connect.WithSchema(atlasServiceMethods.ByName("GetRecord")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atlas.AtlasService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AtlasServiceGetRecordProcedure:
			atlasServiceGetRecordHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAtlasServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAtlasServiceHandler struct{}

func (UnimplementedAtlasServiceHandler) GetRecord(context.Context, *connect.Request[GetRecordRequest]) (*connect.Response[GetRecordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("AtlasService.GetRecord is not implemented"))
}
