// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: atlas.proto

package atlas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRecordRequest specifies which record to retrieve.
// Exactly one of uri or (did + collection + rkey) must be provided.
type GetRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full AT Protocol URI of the record.
	// Format: at://did/collection/rkey
	// Example: at://did:plc:abc123/app.bsky.feed.post/3jxh5pdlwfs2d
	Uri *string `protobuf:"bytes,1,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	// Alternative: specify record by its component parts.
	// The DID of the repository owner (e.g., "did:plc:abc123").
	Did *string `protobuf:"bytes,2,opt,name=did,proto3,oneof" json:"did,omitempty"`
	// The collection NSID (e.g., "app.bsky.feed.post").
	Collection *string `protobuf:"bytes,3,opt,name=collection,proto3,oneof" json:"collection,omitempty"`
	// The record key within the collection (e.g., "3jxh5pdlwfs2d").
	Rkey          *string `protobuf:"bytes,4,opt,name=rkey,proto3,oneof" json:"rkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecordRequest) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *GetRecordRequest) GetDid() string {
	if x != nil && x.Did != nil {
		return *x.Did
	}
	return ""
}

func (x *GetRecordRequest) GetCollection() string {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return ""
}

func (x *GetRecordRequest) GetRkey() string {
	if x != nil && x.Rkey != nil {
		return *x.Rkey
	}
	return ""
}

// GetRecordResponse contains the retrieved record.
type GetRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record data. Nil if not found.
	Record        *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_atlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// Record represents a single ATProto record.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The AT Protocol URI of this record.
	// Format: at://did/collection/rkey
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	// The CID (Content Identifier) of this record version.
	Cid string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	// The DID of the repository owner.
	Did string `protobuf:"bytes,3,opt,name=did,proto3" json:"did,omitempty"`
	// The collection NSID (e.g., "app.bsky.feed.post").
	Collection string `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	// The record key within the collection.
	Rkey string `protobuf:"bytes,5,opt,name=rkey,proto3" json:"rkey,omitempty"`
	// The record value as JSON-encoded bytes.
	// ATProto records are natively CBOR, but JSON is more convenient for clients.
	Value []byte `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	// Unix timestamp (seconds) when this record was indexed by Atlas.
	IndexedAt int64 `protobuf:"varint,7,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	// Unix timestamp (seconds) when this record was created, if available.
	// This is extracted from the record's createdAt field when present.
	CreatedAt     *int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_atlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_atlas_proto_rawDescGZIP(), []int{2}
}

func (x *Record) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Record) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Record) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Record) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Record) GetRkey() string {
	if x != nil {
		return x.Rkey
	}
	return ""
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetIndexedAt() int64 {
	if x != nil {
		return x.IndexedAt
	}
	return 0
}

func (x *Record) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

var File_atlas_proto protoreflect.FileDescriptor

const file_atlas_proto_rawDesc = "" +
	"\n" +
	"\vatlas.proto\x12\x05atlas\"\xa6\x01\n" +
	"\x10GetRecordRequest\x12\x15\n" +
	"\x03uri\x18\x01 \x01(\tH\x00R\x03uri\x88\x01\x01\x12\x15\n" +
	"\x03did\x18\x02 \x01(\tH\x01R\x03did\x88\x01\x01\x12#\n" +
	"\n" +
	"collection\x18\x03 \x01(\tH\x02R\n" +
	"collection\x88\x01\x01\x12\x17\n" +
	"\x04rkey\x18\x04 \x01(\tH\x03R\x04rkey\x88\x01\x01B\x06\n" +
	"\x04_uriB\x06\n" +
	"\x04_didB\r\n" +
	"\v_collectionB\a\n" +
	"\x05_rkey\":\n" +
	"\x11GetRecordResponse\x12%\n" +
	"\x06record\x18\x01 \x01(\v2\r.atlas.RecordR\x06record\"\xda\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x10\n" +
	"\x03did\x18\x03 \x01(\tR\x03did\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04rkey\x18\x05 \x01(\tR\x04rkey\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"indexed_at\x18\a \x01(\x03R\tindexedAt\x12\"\n" +
	"\n" +
	"created_at\x18\b \x01(\x03H\x00R\tcreatedAt\x88\x01\x01B\r\n" +
	"\v_created_at2N\n" +
	"\fAtlasService\x12>\n" +
	"\tGetRecord\x12\x17.atlas.GetRecordRequest\x1a\x18.atlas.GetRecordResponseB%Z#github.com/jcalabro/atlas/pkg/atlasb\x06proto3"

var (
	file_atlas_proto_rawDescOnce sync.Once
	file_atlas_proto_rawDescData []byte
)

func file_atlas_proto_rawDescGZIP() []byte {
	file_atlas_proto_rawDescOnce.Do(func() {
		file_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)))
	})
	return file_atlas_proto_rawDescData
}

var file_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atlas_proto_goTypes = []any{
	(*GetRecordRequest)(nil),  // 0: atlas.GetRecordRequest
	(*GetRecordResponse)(nil), // 1: atlas.GetRecordResponse
	(*Record)(nil),            // 2: atlas.Record
}
var file_atlas_proto_depIdxs = []int32{
	2, // 0: atlas.GetRecordResponse.record:type_name -> atlas.Record
	0, // 1: atlas.AtlasService.GetRecord:input_type -> atlas.GetRecordRequest
	1, // 2: atlas.AtlasService.GetRecord:output_type -> atlas.GetRecordResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_atlas_proto_init() }
func file_atlas_proto_init() {
	if File_atlas_proto != nil {
		return
	}
	file_atlas_proto_msgTypes[0].OneofWrappers = []any{}
	file_atlas_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_proto_rawDesc), len(file_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atlas_proto_goTypes,
		DependencyIndexes: file_atlas_proto_depIdxs,
		MessageInfos:      file_atlas_proto_msgTypes,
	}.Build()
	File_atlas_proto = out.File
	file_atlas_proto_goTypes = nil
	file_atlas_proto_depIdxs = nil
}
